// generated by stringer -output=string.go -type=ChassisIDSubtype,PortIDSubtype; DO NOT EDIT

package lldp

import "fmt"

const _ChassisIDSubtype_name = "ChassisIDSubtypeReservedChassisIDSubtypeChassisComponenentChassisIDSubtypeInterfaceAliasChassisIDSubtypePortComponentChassisIDSubtypeMACAddressChassisIDSubtypeNetworkAddressChassisIDSubtypeInterfaceNameChassisIDSubtypeLocallyAssigned"

var _ChassisIDSubtype_index = [...]uint8{0, 24, 58, 88, 117, 143, 173, 202, 233}

func (i ChassisIDSubtype) String() string {
	if i >= ChassisIDSubtype(len(_ChassisIDSubtype_index)-1) {
		return fmt.Sprintf("ChassisIDSubtype(%d)", i)
	}
	return _ChassisIDSubtype_name[_ChassisIDSubtype_index[i]:_ChassisIDSubtype_index[i+1]]
}

const _PortIDSubtype_name = "PortIDSubtypeReservedPortIDSubtypeInterfaceAliasPortIDSubtypePortComponentPortIDSubtypeMACAddressPortIDSubtypeNetworkAddressPortIDSubtypeInterfaceNamePortIDSubtypeAgentCircuitIDPortIDSubtypeLocallyAssigned"

var _PortIDSubtype_index = [...]uint8{0, 21, 48, 74, 97, 124, 150, 177, 205}

func (i PortIDSubtype) String() string {
	if i >= PortIDSubtype(len(_PortIDSubtype_index)-1) {
		return fmt.Sprintf("PortIDSubtype(%d)", i)
	}
	return _PortIDSubtype_name[_PortIDSubtype_index[i]:_PortIDSubtype_index[i+1]]
}
